# version: '3'
# services:
#   commercial:
#     image: commercial
#   db:
#     image: mysql
#     ports:
#     - "3306:3306"
#     environment:
#     - MYSQL_ROOT_PASSWORD=password
#     - MYSQL_USER=root
#     - MYSQL_PASSWORD=0435
#     - MYSQL_DATABASE=demodb


version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: authuserDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 0435
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  commercial:
    build: .
    container_name: commercial
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - mysqldb
    environment:
      - DATABASE_NAME=authuserDB
      - DATABASE_USER=root
      - DATABASE_PASSWORD=0435
      - DATABASE_HOST=db
      - DATABASE_PORT=3306

volumes:
  db_data:
